### PR TITLE
Correctly handle errors from server

### PR DESCRIPTION
**Pull request by brianmay**
Previously we would treat errors as non-errors and then crash trying to parse the error data.

### CODE REVIEW

**Comment by brianmay** [comment]
As referenced in #1.

**Comment by hepcat72** [comment]
The merge button never loads on my phone or I'd merge it right now.

**Comment by brianmay** [comment]
I fixed the conflicts.

**Comment by hepcat72** [comment]
I assumed you had with that last push. I'll merge when I'm not out on my phone, because all GitHub gives me is a spinning circle instead of a status and merge option:

image

**Comment by MaksimShakavin** [comment]
Will you also push an update to npm?

**Comment by hepcat72** [comment]
Yes. Not sure when though.  You can install via github however...

**Pull request merged**
