### PR TITLE
fix property 'status' of undefined error

### PR DESCRIPTION
**Pull request by MaksimShakavin**
Fix an issue that was pointed in https://github.com/hepcat72/node-red-contrib-life360/pull/10

### CODE REVIEW

**Review by hepcat72 — APPROVED** [review]
Aha. Makes sense that the response would not exist if there was an error in the request.

**Comment by MaksimShakavin** [comment]
@hepcat72 , exactly
Could you also please publish it to npm when this one is merged? I've already changed the minor version in the previous PR

**Comment by MaksimShakavin** [comment]
ping @hepcat72 @brianmay

**Comment by hepcat72** [comment]
Hey @MaksimShakavin, I merged this PR.  Sorry for the slow response.  I just installed the latest version (since you and @brianmay started contributing.  I'm going to let it run for awhile before I create a new release so that I can confirm it's stable first-hand before pushing out a new version.

Note, since I was working on it, I saw a new error that started showing up in my logs since October (#13).  I just pushed a fix for that, if you're seeing that too.

**Pull request merged**
